<img width="950" height="960" alt="Image" src="https://github.com/user-attachments/assets/1962226a-6a31-4aa1-86cb-715babadb177" />
title: John Barry V. Blase
logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
